[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_internal_expect_revert = true

remappings = [
	"forge-std/=lib/forge-std/src/",
	"permit2/=lib/permit2/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
