[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_internal_expect_revert = true
dynamic_test_linking = true
fuzz.runs = 5000
optimizer = true
optimizer_runs = 999999
verbosity = 2
via_ir = true

remappings = [
	"forge-std/=lib/forge-std/src/",
	"permit2/=lib/permit2/src/"
]

[fmt]
line_length = 120
tab_width = 4
func_attrs_with_params_multiline = true
inline_attribute_style = "compact"
multiline_func_header = "params_first"
return_statement = "inline"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
